# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardpost",
            name="board_type",
            field=models.CharField(
                choices=[("NOTICE", "공지사항"), ("FREE", "자유게시판"), ("DATA_ROOM", "자료실")],
                default="FREE",
                max_length=30,
            ),
        ),
    ]
