# Generated by Codex on 2026-06-29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boards", "0003_alter_boardpost_board_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardpost",
            name="permission",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "전체공개"),
                    ("DEPARTMENT", "부서공개"),
                    ("SPECIFIC", "지정인원"),
                ],
                default="PUBLIC",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="boardpost",
            name="specific_users",
            field=models.ManyToManyField(blank=True, related_name="permitted_board_posts", to=settings.AUTH_USER_MODEL),
        ),
    ]
