# Generated by Django 6.0.6 on 2026-06-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('WORK', '업무'), ('MEETING', '회의'), ('TODO', '할일'), ('WORK_REQUEST', '업무요청')], max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(default='#4A90D9', max_length=7)),
                ('alert_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.CharField(choices=[('PENDING', '대기'), ('ACCEPTED', '참석'), ('DECLINED', '불참'), ('TENTATIVE', '미정')], default='PENDING', max_length=20)),
            ],
        ),
    ]
