# Generated by Codex on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_optional_end_and_free_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="is_all_day",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schedule",
            name="repeat_type",
            field=models.CharField(
                choices=[
                    ("NONE", "반복 안함"),
                    ("DAILY", "매일"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
    ]
