# Generated by Codex on 2026-06-29

from django.conf import settings
from django.db import migrations, models


def copy_primary_assignee_to_many(apps, schema_editor):
    WorkRequest = apps.get_model("work_requests", "WorkRequest")
    for work_request in WorkRequest.objects.exclude(assignee_id=None):
        work_request.assignees.add(work_request.assignee_id)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("work_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workrequest",
            name="assignees",
            field=models.ManyToManyField(blank=True, related_name="multi_assigned_work_requests", to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copy_primary_assignee_to_many, migrations.RunPython.noop),
    ]
