# Generated by Codex on 2026-06-29

from django.db import migrations, models


def daily_to_work(apps, schema_editor):
    Report = apps.get_model("reports", "Report")
    Report.objects.filter(report_type="DAILY_REPORT").update(report_type="WORK_REPORT")


def work_to_daily(apps, schema_editor):
    Report = apps.get_model("reports", "Report")
    Report.objects.filter(report_type="WORK_REPORT").update(report_type="DAILY_REPORT")


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(daily_to_work, work_to_daily),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("WORK_REPORT", "업무보고"),
                    ("WEEKLY_REPORT", "주간보고"),
                    ("MONTHLY_REPORT", "월간보고"),
                    ("EXPENSE_REPORT", "경비지출"),
                ],
                max_length=30,
            ),
        ),
    ]
