# Generated by Codex on 2026-06-29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0003_unify_daily_report_to_work_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="recipients",
            field=models.ManyToManyField(blank=True, related_name="received_reports", to=settings.AUTH_USER_MODEL),
        ),
    ]
