# Generated by Codex on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_biometricchallenge_biometriccredential"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hire_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
